compile:
	npx hardhat compile

deploy:
	npx hardhat run ignition/modules/Nebula.ts --network mantleSepolia

verify:
	npx hardhat verify --network mantleSepolia 0xDE115676F736F154eEF8398A37e4ACB4d61892e6